### ISSUE TITLE
Job is not getting triggered

### ISSUE THREAD

**Issue by pgbidkar** [webhookrelay/webhookrelayd#25]
Followed exact steps in this link https://webhookrelay.com/intro/github/jenkins/webhooks/automation/2017/05/22/github-jenkins-guide/

relayd is running

WARN[1130] relayer: unexpected status code               destination=http://<IP>/job/Test-WebHook/ method=POST status_code=403
INFO[1130] webhook request relayed                       bucket=Jenkins-WebHook-Test destination=http://<IP>/job/Test-WebHook/

Status in WebHook log shows "SENT"

But Jenkins Job is not getting triggered?

**Comment by rusenask** [comment]
It seems your destination is wrong, jenkis github plugin expects incoming
webhooks to hit http://yourjenkins:8080/github-webook/ endpoint.
Also, is "job" a hostname for jenkins?

PS: all repos will have to go to the same endpoint on jenkins.

**Comment by pgbidkar** [comment]
Sorry its a typo, destination looks like this http://myjenkinsserver:8080/job/Test-WebHook/

so destination should be like http://myjenkinsserver:8080/github-webhook or each every Jenkins server will have its own webhook URL?

**Comment by pgbidkar** [comment]
Thanks a lot. Changes output as http://myjenkinsserver:8080/github-webhook, Job got triggered successfully

**Comment by pgbidkar** [comment]
Does this work for pipeline jobs as well? any other configuration required for pipeline jobs?

**Comment by rusenask** [comment]
Haven't tried but as long as pipeline can be triggered by a webhook - it
should work.
